name: otus_food
description: otus_food
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  collection: any

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.7
  get: ^4.6.6
  get_it: ^7.6.4
  sbp: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  build_runner: ^2.4.6


flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/

  fonts:
    - family: Roboto-Bold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: Roboto-BoldItalic
      fonts:
        - asset: assets/fonts/Roboto-BoldItalic.ttf
    - family: Roboto-Italic
      fonts:
        - asset: assets/fonts/Roboto-Italic.ttf
    - family: Roboto-Light
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
    - family: Roboto-LightItalic
      fonts:
        - asset: assets/fonts/Roboto-LightItalic.ttf
    - family: Roboto-Medium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
    - family: Roboto-MediumItalic
      fonts:
        - asset: assets/fonts/Roboto-MediumItalic.ttf
    - family: Roboto-Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Roboto-Thin
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf